import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../component/Navbar";
import Footer from "../component/Footer";
import Head from "next/head";
import Link from "next/link";
import "./header.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* <script src="https://cdn.tailwindcss.com"></script> */}
      </Head>
      <body className={inter.className}>
        <Navbar />

        <div>{children}</div>


        <Footer />
      </body>


    </html>
  );
}
